In [15]:
import numpy as np
import pandas as pd

from models import MELsModel
from tqdm import tqdm

import time


import sys
sys.path.append('/home/wanfu/Documents/midea4/Midea-DR-Project/') 
# you need to add your own absolute project path to resolve the relative import problems 
# reference https://blog.csdn.net/weixin_41699811/article/details/84965328
# '/home/wanfu/Documents/midea4/Midea-DR-Project/' means absolute project path

## The MELsModel class with heuristic method has two ways to use

### 1. Just use it for prediction, which is also the way we will use **<font color = red>most frequently</font>** later in open loop control
+ On this conditon, we should set parammeter **validate**=False

+ Set **method**='heuristic'

+ The paramter **timeStamp** means you want the future 24 hours prediction after this **timeStamp**. For example, if **timeStamp**=pd.to_datetime(**<font color = red>'2022-11-25 01:00:00'</font>**), the model will return the prediction value of **<font color = red>'2022-11-25 02:00:00','2022-11-25 03:00:00', ...... ,'2022-11-26 01:00:00'</font>** , which are total 24 time steps. We will return a dataframe with time index

In [10]:
MELs_model=MELsModel()

y_pred_df=MELs_model.one_day_MELs_predict(method='heuristic',
                                          timeStamp=pd.to_datetime('2022-11-25 01:00:00'),
                                          validate=False)

y_pred_df

                     E_diff
2022-11-25 02:00:00   6.213
2022-11-25 03:00:00   6.147
2022-11-25 04:00:00   6.176
2022-11-25 05:00:00   6.757
2022-11-25 06:00:00   9.874
2022-11-25 07:00:00  10.042
2022-11-25 08:00:00  10.850
2022-11-25 09:00:00  14.176
2022-11-25 10:00:00  14.498
2022-11-25 11:00:00  14.367
2022-11-25 12:00:00  10.945
2022-11-25 13:00:00   7.072
2022-11-25 14:00:00  13.425
2022-11-25 15:00:00  14.018
2022-11-25 16:00:00  14.301
2022-11-25 17:00:00  13.984
2022-11-25 18:00:00  13.689
2022-11-25 19:00:00  12.605
2022-11-25 20:00:00  11.341
2022-11-25 21:00:00  10.187
2022-11-25 22:00:00   8.696
2022-11-25 23:00:00   7.339
2022-11-26 00:00:00   6.654
2022-11-26 01:00:00   6.162

### 2. When we set parameter **validate**=True, we can validate the heuristic model, this application only be used when we are developing the  heuristic model, we want to know its performance. It will return dataframe and square_error of this timestamp prediction

In [11]:
MELs_model=MELsModel()

y_pred_df,square_error=MELs_model.one_day_MELs_predict(method='heuristic',
                                          timeStamp=pd.to_datetime('2022-11-25 01:00:00'),
                                          validate=True)

y_pred_df

                     E_diff
2022-11-25 02:00:00   6.213
2022-11-25 03:00:00   6.147
2022-11-25 04:00:00   6.176
2022-11-25 05:00:00   6.757
2022-11-25 06:00:00   9.874
2022-11-25 07:00:00  10.042
2022-11-25 08:00:00  10.850
2022-11-25 09:00:00  14.176
2022-11-25 10:00:00  14.498
2022-11-25 11:00:00  14.367
2022-11-25 12:00:00  10.945
2022-11-25 13:00:00   7.072
2022-11-25 14:00:00  13.425
2022-11-25 15:00:00  14.018
2022-11-25 16:00:00  14.301
2022-11-25 17:00:00  13.984
2022-11-25 18:00:00  13.689
2022-11-25 19:00:00  12.605
2022-11-25 20:00:00  11.341
2022-11-25 21:00:00  10.187
2022-11-25 22:00:00   8.696
2022-11-25 23:00:00   7.307
2022-11-26 00:00:00   6.654
2022-11-26 01:00:00   6.168

In [12]:
square_error**0.5

1.4643403619555713


#### Example code： get heuristic model rmse
This is not a formal way to evaluate a model, but we can get a rough idea about the permance of heuristic model

In [13]:
# evaluation data time range
t_range=pd.date_range(pd.to_datetime('2022-08-01 00:00:00'),pd.to_datetime('2022-11-25 00:00:00'),freq='1D')
square_errors=[]

MELs_model=MELsModel()



for t in tqdm(t_range):

    _,square_error=MELs_model.one_day_MELs_predict(method='heuristic',
                                      timeStamp=t,
                                      validate=True)
    square_errors.append(square_error)

  0%|                                                   | 0/117 [00:00<?, ?it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
  1%|▎                                          | 1/117 [00:00<01:32,  1.26it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
  2%|▋                                          | 2/117 [00:01<01:33,  1.24it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
  3%|█                                          | 3/117 [00:02<01:28,  1.30it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
  3%|█▍                                         | 4/117 [00:03<01:29,  1.27it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
  4%|█▊                                         | 5/117 [00:03<01:29,  1.25it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
  5%|██▏                                        | 6/117 [00:04<01:29,  1.23it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
  6%|██▌                                        | 7/117 [00:05<01:28,  1.24it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
  7%|██▉                                        | 8/117 [00:06<01:26,  1.26it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
  8%|███▎                                       | 9/117 [00:07<01:25,  1.26it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
  9%|███▌                                      | 10/117 [00:07<01:24,  1.26it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
  9%|███▉                                      | 11/117 [00:08<01:26,  1.23it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 10%|████▎                                     | 12/117 [00:09<01:18,  1.33it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 11%|████▋                                     | 13/117 [00:11<01:55,  1.11s/it]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 12%|█████                                     | 14/117 [00:12<01:44,  1.01s/it]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 13%|█████▍                                    | 15/117 [00:12<01:37,  1.05it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 14%|█████▋                                    | 16/117 [00:13<01:27,  1.15it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 15%|██████                                    | 17/117 [00:14<01:17,  1.29it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 15%|██████▍                                   | 18/117 [00:14<01:12,  1.36it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 16%|██████▊                                   | 19/117 [00:15<01:07,  1.45it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 17%|███████▏                                  | 20/117 [00:15<01:02,  1.54it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 18%|███████▌                                  | 21/117 [00:16<00:59,  1.62it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 20%|████████▎                                 | 23/117 [00:17<00:54,  1.72it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 21%|████████▌                                 | 24/117 [00:18<00:50,  1.83it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 21%|████████▉                                 | 25/117 [00:18<00:51,  1.79it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 22%|█████████▎                                | 26/117 [00:19<00:48,  1.89it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 23%|█████████▋                                | 27/117 [00:19<00:47,  1.88it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 73%|██████████████████████████████▌           | 85/117 [00:51<00:18,  1.70it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 74%|██████████████████████████████▊           | 86/117 [00:52<00:17,  1.76it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 74%|███████████████████████████████▏          | 87/117 [00:53<00:19,  1.55it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 75%|███████████████████████████████▌          | 88/117 [00:53<00:16,  1.72it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
 76%|███████████████████████████████▉          | 89/117 [00:54<00:15,  1.76it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)

 77%|████████████████████████████████▎         | 90/117 [00:54<00:15,  1.74it/s]/home/wanfu/Documents/midea4/Midea-DR-Project/model/models.py:563: RuntimeWarning: Mean of empty slice
  square_error = np.nanmean((np.array(y_true) - np.array(y_pred)) ** 2)
100%|█████████████████████████████████████████| 117/117 [01:12<00:00,  1.61it/s]

In [14]:
rmse=np.nanmean(square_errors)**0.5
rmse

4.0087901161269075